### ISSUE TITLE
Menu.sh

### ISSUE THREAD

**Issue by NatoBoram** [SpigotMCUpdater/SpigotMC-Updater#1]
Looks like you guys decided to do a menu. Why not update everything without asking any question?

**Comment by Legoman99573** [comment]
I recoded Buildtools Updater (Windows Only) with a good cleanup. Should work now. If you want to use a different os, then im good.

**Comment by NatoBoram** [comment]
When comparing [menu.sh](https://github.com/SpigotMCUpdater/SpigotMC-Updater/blob/master/menu.sh) with [BuildTools.sh](https://github.com/SpigotMCUpdater/SpigotMC-Updater/blob/master/BuildTools.sh), I see that the only difference is the user interaction in [menu.sh](https://github.com/SpigotMCUpdater/SpigotMC-Updater/blob/master/menu.sh) and the use of _java -jar BuildTools.jar_ is nowhere in the code. Still I am asking : Why use a menu?
